#!/bin/sh
echo "enter a file name"
read name
if test -f $name
then
	if test -w $name
	then
		echo "type what you want to add, ctrl+d to exist"
	cat >> $name
	else
		echo "you dont have permission to write"
	fi
fi


