#!/bin/sh
echo "Enter a char"
read char
case $char in
[a-z])
	echo "you entered a lower case"
	;;
[A-Z])
	echo "you entered a upper case"
	;;
[0-9])
	echo "you entered a digit"
	;;
?)
	echo "you entered a special sympol"
	;;
*)
	echo "you entered more than one char"
	;;
esac
