#!/bin/sh
echo "enter a number between 10 and 20"
read num
if [ $num -lt 10 ]
then
	echo "the number is less than 10"

elif [ $num -gt 20 ]
then
	echo "the number is greater than 20"

else
	echo "the number is between 10 and 20"
fi
